"""Update relation rights_users

Revision ID: 74b6803d2e05
Revises: afaf471a233d
Create Date: 2022-04-18 20:55:33.718445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '74b6803d2e05'
down_revision = 'afaf471a233d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles_rights', 'role_uuid',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('roles_rights', 'right_uuid',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles_rights', 'right_uuid',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('roles_rights', 'role_uuid',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###
